# docker-compose.yml

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/music_db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:5000/api
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  test:
    build: 
      context: ./backend/tests
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/music_db
    depends_on:
      - mongo
      - backend
    profiles:
      - donotstart

volumes:
  mongodb_data:
    driver: local
