---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-copier
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: mongodb
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mongodb"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-mongodb-secret
  namespace: mongodb
subjects:
  - kind: ServiceAccount
    name: secret-copier
    namespace: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-app-secret
  namespace: default
subjects:
  - kind: ServiceAccount
    name: secret-copier
    namespace: default
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
