apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-app-backend.fullname" . }}
  labels:
    app: {{ include "music-app-backend.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ include "music-app-backend.name" . }}
