fullnameOverride: "music-app-backend"
nameOverride: ""

replicaCount: 1

image:
  repository: idoshoshani123/music-app-backend
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  MONGO_URI: "mongodb://mongo.mongodb.svc.cluster.local:27017/music_db"

resources: {}
