fullnameOverride: "music-app-backend"
nameOverride: ""

replicaCount: 1

image:
  repository: idoshoshani123/music-app-backend
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  MONGO_URI: "mongodb://mongo.mongodb.svc.cluster.local:27017/music_db"

resources: {}

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
