fullnameOverride: "music-app-backend"
nameOverride: ""

replicaCount: 1

image:
  repository: idoshoshani123/music-app-backend
  tag: "31"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources: {}

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 5
